<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hotel</groupId>
    <artifactId>hotel-booking-system</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <name>hotel-booking-system</name>

    <!-- MODULES -->
    <modules>
        <module>discovery-server</module>
        <module>api-gateway</module>
        <module>user-auth-service</module>
        <module>hotel-service</module>
    </modules>

    <!-- COMMON PROPERTIES -->
    <properties>
        <java.version>17</java.version>
        <spring.boot.version>3.2.5</spring.boot.version>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
    </properties>

    <!-- DEPENDENCY MANAGEMENT -->
    <dependencyManagement>
        <dependencies>

            <!-- SPRING BOOT -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- SPRING CLOUD -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>