spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:

        # AUTH SERVICE
        - id: USER-AUTH-SERVICE
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # HOTEL + BOOKING + REVIEW
        - id: HOTEL-BOOKING-SERVICE
          uri: lb://HOTEL-BOOKING-SERVICE
          predicates:
            - Path=/hotels/**,/bookings/**,/reviews/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
server:
  port: 8080


